### ISSUE TITLE
Missing multi part upload

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-s3#29] opened 2015-04-29 11:04 UTC
Right now jcabi-s3 doesn't have multi part upload feature (see http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html for reference). 
It prohibits uploading of large files, as they have to be buffered in memory (to calculate file size) before being uploaded to S3.

**Comment by dmarkov** [comment] 2015-05-26 07:19
@krzyk we will find someone to do this task, soon

**Comment by dmarkov** [comment] 2015-05-26 07:20
@krzyk thank you for the ticket reported, I topped your account for 15 mins, transaction `58052960`

**Comment by dmarkov** [comment] 2015-09-11 07:03
@yamstranger the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by YamStranger** [comment] 2015-09-15 07:19
@dmarkov please assign to reviewer. Thanks

**Comment by dmarkov** [comment] 2015-09-15 10:59
> @dmarkov please assign to reviewer. Thanks

@yamstranger np :)

**Comment by YamStranger** [comment] 2015-09-18 05:04
@dmarkov Is this issue fixed?

**Comment by YamStranger** [comment] 2015-09-18 16:21
@dmarkov It seems that PR #35 for this issue already merged, so it can be closed?

**Comment by krzyk** [comment] 2015-09-18 16:42
@YamStranger you have to ask issue creator for closing, so in this case me :), let me check the changes and I'll close

**Comment by YamStranger** [comment] 2015-09-18 16:44
@krzyk Thanks

**Closed** 2015-09-18 18:43 UTC
Labels: 30 mins, @yamstranger, bug, DEV

**Comment by dmarkov** [comment] 2015-09-21 09:28
> @dmarkov Is this issue fixed?

@yamstranger you should ask @krzyk, he is the author of the ticket

**Comment by YamStranger** [comment] 2015-09-21 12:28
@dmarkov, @krzyk closed it three days ago

**Comment by dmarkov** [comment] 2015-09-22 10:04
@yamstranger **30 mins** sent to your balance (ID `65747135`), many thanks! It took 242 hours and 26 mins.... added +30 to your rating, now it is equal to [-30](http://www.netbout.com/b/35267?open=rating)

**Comment by YamStranger** [comment] 2015-09-22 10:09
@dmarkov Thanks!!!!

**Comment by dmarkov** [comment] 2015-09-22 12:20
> @dmarkov Thanks!!!!
> 

@yamstranger no problem ;)
